2025-07-26 01:56:19 ERROR Traceback (most recent call last):
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
ValueError: Sweep username/projectname/xxxxxx not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mlops-course\venv\lib\site-packages\wandb\cli\cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\cli\cli.py", line 1755, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 570, in agent
    return run_agent(
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 528, in run_agent
    agent.run()
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
wandb.errors.CommError: Sweep username/projectname/xxxxxx not found

2025-07-26 02:56:03 ERROR 400 response executing GraphQL.
2025-07-26 02:56:03 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2025-07-26 02:56:03 ERROR Traceback (most recent call last):
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1055, in sweep
    response = self.gql(
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\mlops-course\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\mlops-course\venv\lib\site-packages\requests\models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mlops-course\venv\lib\site-packages\wandb\cli\cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\cli\cli.py", line 1755, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 570, in agent
    return run_agent(
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 528, in run_agent
    agent.run()
  File "C:\mlops-course\venv\lib\site-packages\wandb\wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "C:\mlops-course\venv\lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: name required for project query (Error 400: Bad Request)

2025-07-26 03:03:37 INFO Running runs: []
2025-07-26 03:03:37 INFO Agent received command: run
2025-07-26 03:03:37 INFO Agent starting run with config:
	alpha: 1
	test_size: 0.31609734803264744
2025-07-26 03:03:37 INFO About to run command: python train.py --alpha=1 --test_size=0.31609734803264744
2025-07-26 03:03:42 INFO Running runs: ['povki2mo']
2025-07-26 03:03:42 INFO Cleaning up finished run: povki2mo
2025-07-26 03:03:43 INFO Agent received command: run
2025-07-26 03:03:43 INFO Agent starting run with config:
	alpha: 1
	test_size: 0.15276296470236317
2025-07-26 03:03:43 INFO About to run command: python train.py --alpha=1 --test_size=0.15276296470236317
2025-07-26 03:03:48 INFO Running runs: ['o3vqa8h9']
2025-07-26 03:03:48 INFO Cleaning up finished run: o3vqa8h9
2025-07-26 03:03:48 INFO Agent received command: run
2025-07-26 03:03:48 INFO Agent starting run with config:
	alpha: 2
	test_size: 0.3836976132377785
2025-07-26 03:03:48 INFO About to run command: python train.py --alpha=2 --test_size=0.3836976132377785
2025-07-26 03:03:53 INFO Running runs: ['jjqxwgyr']
2025-07-26 03:03:53 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2025-07-26 03:03:53 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2025-07-26 23:52:54 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:54 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:54 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:54 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:54 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:55 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:55 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:55 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:56 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:56 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:52:59 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-26 23:53:00 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-26 23:53:00 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-26 23:53:00 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-27 00:54:02 INFO Running runs: []
2025-07-27 00:54:02 INFO Agent received command: run
2025-07-27 00:54:02 INFO Agent starting run with config:
	C: 0.1
	max_features: 5000
	ngram_range: [1, 1]
2025-07-27 00:54:02 INFO About to run command: python scripts/train_logistic_wandb.py --C=0.1 --max_features=5000 "--ngram_range=[1, 1]"
2025-07-27 00:54:07 INFO Running runs: ['ilgwcbm1']
2025-07-27 00:54:13 INFO Cleaning up finished run: ilgwcbm1
2025-07-27 00:54:13 INFO Agent received command: run
2025-07-27 00:54:13 INFO Agent starting run with config:
	C: 0.1
	max_features: 5000
	ngram_range: [1, 2]
2025-07-27 00:54:13 INFO About to run command: python scripts/train_logistic_wandb.py --C=0.1 --max_features=5000 "--ngram_range=[1, 2]"
2025-07-27 00:54:18 INFO Running runs: ['dki9qbjl']
2025-07-27 00:54:29 INFO Cleaning up finished run: dki9qbjl
2025-07-27 00:54:29 INFO Agent received command: run
2025-07-27 00:54:29 INFO Agent starting run with config:
	C: 0.1
	max_features: 10000
	ngram_range: [1, 1]
2025-07-27 00:54:29 INFO About to run command: python scripts/train_logistic_wandb.py --C=0.1 --max_features=10000 "--ngram_range=[1, 1]"
2025-07-27 00:54:34 INFO Running runs: ['g6br7b0o']
2025-07-27 00:54:40 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2025-07-27 00:54:40 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2025-07-27 00:59:13 INFO Running runs: []
2025-07-27 00:59:13 INFO Agent received command: run
2025-07-27 00:59:13 INFO Agent starting run with config:
	C: 0.1
	max_features: 10000
	ngram_range: [1, 2]
2025-07-27 00:59:13 INFO About to run command: python scripts/train_logistic_wandb.py --C=0.1 --max_features=10000 "--ngram_range=[1, 2]"
2025-07-27 00:59:18 INFO Running runs: ['dt4chz5k']
2025-07-27 00:59:24 INFO Cleaning up finished run: dt4chz5k
2025-07-27 00:59:24 INFO Agent received command: run
2025-07-27 00:59:24 INFO Agent starting run with config:
	C: 1
	max_features: 5000
	ngram_range: [1, 1]
2025-07-27 00:59:24 INFO About to run command: python scripts/train_logistic_wandb.py --C=1 --max_features=5000 "--ngram_range=[1, 1]"
2025-07-27 00:59:29 INFO Running runs: ['xzui4fo4']
2025-07-27 00:59:41 INFO Cleaning up finished run: xzui4fo4
2025-07-27 00:59:41 INFO Agent received command: run
2025-07-27 00:59:41 INFO Agent starting run with config:
	C: 1
	max_features: 5000
	ngram_range: [1, 2]
2025-07-27 00:59:41 INFO About to run command: python scripts/train_logistic_wandb.py --C=1 --max_features=5000 "--ngram_range=[1, 2]"
2025-07-27 00:59:46 INFO Running runs: ['0is2w5v7']
2025-07-27 00:59:57 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2025-07-27 00:59:57 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2025-07-27 01:02:59 INFO Running runs: []
2025-07-27 01:03:00 INFO Agent received command: run
2025-07-27 01:03:00 INFO Agent starting run with config:
	C: 1
	max_features: 10000
	ngram_range: [1, 1]
2025-07-27 01:03:00 INFO About to run command: python scripts/train_logistic_wandb.py --C=1 --max_features=10000 "--ngram_range=[1, 1]"
2025-07-27 01:03:05 INFO Running runs: ['oskgn25m']
2025-07-27 01:03:05 INFO Cleaning up finished run: oskgn25m
2025-07-27 01:03:05 INFO Agent received command: run
2025-07-27 01:03:05 INFO Agent starting run with config:
	C: 1
	max_features: 10000
	ngram_range: [1, 2]
2025-07-27 01:03:05 INFO About to run command: python scripts/train_logistic_wandb.py --C=1 --max_features=10000 "--ngram_range=[1, 2]"
2025-07-27 01:03:10 INFO Running runs: ['7h6xbd6g']
2025-07-27 01:03:21 INFO Cleaning up finished run: 7h6xbd6g
2025-07-27 01:03:21 INFO Agent received command: run
2025-07-27 01:03:21 INFO Agent starting run with config:
	C: 10
	max_features: 5000
	ngram_range: [1, 1]
2025-07-27 01:03:21 INFO About to run command: python scripts/train_logistic_wandb.py --C=10 --max_features=5000 "--ngram_range=[1, 1]"
2025-07-27 01:03:26 INFO Running runs: ['rpun9zn9']
2025-07-27 01:03:31 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2025-07-27 01:03:31 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2025-07-27 01:10:48 INFO Running runs: []
2025-07-27 01:10:48 INFO Agent received command: run
2025-07-27 01:10:48 INFO Agent starting run with config:
	C: 10
	max_features: 5000
	ngram_range: [1, 2]
2025-07-27 01:10:48 INFO About to run command: python scripts/train_logistic_wandb.py --C=10 --max_features=5000 "--ngram_range=[1, 2]"
2025-07-27 01:10:53 INFO Running runs: ['olrjssj2']
2025-07-27 01:10:53 INFO Cleaning up finished run: olrjssj2
2025-07-27 01:10:54 INFO Agent received command: run
2025-07-27 01:10:54 INFO Agent starting run with config:
	C: 10
	max_features: 10000
	ngram_range: [1, 1]
2025-07-27 01:10:54 INFO About to run command: python scripts/train_logistic_wandb.py --C=10 --max_features=10000 "--ngram_range=[1, 1]"
2025-07-27 01:10:59 INFO Running runs: ['vpn3qel5']
2025-07-27 01:11:04 INFO Cleaning up finished run: vpn3qel5
2025-07-27 01:11:05 INFO Agent received command: run
2025-07-27 01:11:05 INFO Agent starting run with config:
	C: 10
	max_features: 10000
	ngram_range: [1, 2]
2025-07-27 01:11:05 INFO About to run command: python scripts/train_logistic_wandb.py --C=10 --max_features=10000 "--ngram_range=[1, 2]"
2025-07-27 01:11:10 INFO Running runs: ['fswph4lx']
2025-07-27 01:11:15 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2025-07-27 01:11:15 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2025-07-27 01:17:02 INFO Running runs: []
2025-07-27 17:03:12 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:13 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:13 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:13 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:13 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:13 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:14 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:15 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:15 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:15 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:16 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:03:17 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-27 17:03:17 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-27 17:08:07 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:07 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:07 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:07 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:07 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:08 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:08 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:08 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:10 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:10 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:10 WARNING Connection pool is full, discarding connection: api.wandb.ai. Connection pool size: 10
2025-07-27 17:08:10 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-27 17:08:12 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2025-07-27 17:08:12 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
